fixtures:
  repositories:
    stdlib:
      repos: "https://github.com/puppetlabs/puppetlabs-stdlib.git"
      # Version is compatible with puppet4/6/7
      ref: "5.2.0"
    apt:
      repo: "https://github.com/puppetlabs/puppetlabs-apt.git"
  symlinks:
    wireguard: "#{source_dir}"
